project_name: zstd-archiver

release:
  name_template: zstd-archiver

builds:
  -
    goos:
      - windows
      - darwin
      - linux

    goarch:
      - 386
      - amd64
      - arm
      - arm64

    goarm:
      - 7

    ignore:
      - goos: darwin
        goarch: 386

archive:
  format: binary

snapshot:
  name_template: wef